import { HttpClient } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';

import { API_CONFIG } from '../../core/api/api.config';
import { extractMessage } from '../../core/http/extract-message';
import { FormPageComponent } from '../../shared/form-page.component';
import { GIFT_CARD_CURRENCIES, type GiftCardCurrency, type GiftCardRow } from './gift-card.types';

/**
 * Issue a gift card, on its own route.
 *
 * The card's code is generated by the server and shown only here, so the
 * page stays put after issuing and displays it, rather than navigating
 * back to a list where the code is one row among many.
 */
@Component({
  selector: 'app-gift-card-form',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, TranslatePipe, FormPageComponent],
  template: `
    @if (issued(); as card) {
      <section style="padding: clamp(16px, 3vw, 28px); max-width: 960px; margin: 0 auto">
        <div
          style="background: var(--color-foam); border: 1px solid var(--color-border-light); border-radius: 18px; padding: clamp(16px, 2.5vw, 24px)"
        >
          <p
            style="font-family: var(--font-sans); font-size: 14px; color: var(--color-text-secondary); margin: 0 0 8px"
          >
            {{ 'admin.giftCards.issuedTitle' | translate }}
          </p>
          <p
            style="font-family: var(--font-mono); font-size: 28px; font-weight: 700; color: var(--color-caramel); margin: 0; user-select: all; word-break: break-all"
          >
            {{ card.code }}
          </p>
        </div>
        <div class="flex items-center flex-wrap" style="gap: 12px; margin-top: 20px">
          <a
            routerLink="/gift-cards"
            style="height: 40px; padding: 0 20px; display: inline-flex; align-items: center; background: var(--color-caramel); color: white; border-radius: var(--radius-button); font-family: var(--font-sans); font-size: 14px; font-weight: 600; text-decoration: none"
          >
            {{ 'admin.giftCards.title' | translate }}
          </a>
          <button
            type="button"
            (click)="again()"
            style="height: 40px; padding: 0 18px; background: var(--color-latte); color: var(--color-espresso); border: 0; border-radius: var(--radius-button); font-family: var(--font-sans); font-size: 14px; font-weight: 600; cursor: pointer"
          >
            {{ 'admin.giftCards.issueCta' | translate }}
          </button>
        </div>
      </section>
    } @else {
      <app-form-page
        [backTo]="['/gift-cards']"
        backLabel="admin.giftCards.title"
        title="admin.giftCards.issueCta"
        saveLabel="admin.giftCards.issueCta"
        [saveDisabled]="form.invalid"
        [saving]="issuing()"
        [error]="error()"
        (save)="issue()"
      >
        <form [formGroup]="form" (ngSubmit)="issue()" class="flex flex-col" style="gap: 14px">
          <div class="form-row">
            <label class="field">
              <span class="field-label">{{ 'admin.giftCards.amount' | translate }}</span>
              <input type="number" min="1" step="0.01" formControlName="amount" class="field-input field-input-mono" />
            </label>
            <label class="field">
              <span class="field-label">{{ 'admin.giftCards.currency' | translate }}</span>
              <select formControlName="currency" class="field-input">
                @for (c of currencies; track c) {
                  <option [value]="c">{{ c }}</option>
                }
              </select>
            </label>
          </div>

          <label class="field">
            <span class="field-label">{{ 'admin.giftCards.recipientEmail' | translate }}</span>
            <input type="email" formControlName="recipientEmail" class="field-input" />
          </label>

          <label class="field">
            <span class="field-label">{{ 'admin.giftCards.message' | translate }}</span>
            <textarea formControlName="message" rows="3" maxlength="500" class="field-input"></textarea>
          </label>
        </form>
      </app-form-page>
    }
  `,
})
export class GiftCardFormPage {
  private readonly http = inject(HttpClient);
  private readonly api = inject(API_CONFIG);
  private readonly translate = inject(TranslateService);

  readonly currencies = GIFT_CARD_CURRENCIES;
  readonly issuing = signal(false);
  readonly issued = signal<GiftCardRow | null>(null);
  readonly error = signal<string | null>(null);

  readonly form = new FormGroup({
    amount: new FormControl<number | null>(null, { validators: [Validators.required, Validators.min(0.01)] }),
    currency: new FormControl<GiftCardCurrency>('USD', { nonNullable: true }),
    recipientEmail: new FormControl('', { nonNullable: true }),
    message: new FormControl('', { nonNullable: true }),
  });

  issue(): void {
    const v = this.form.getRawValue();
    if (!v.amount) return;
    this.issuing.set(true);
    this.error.set(null);
    this.http
      .post<GiftCardRow>(`${this.api.baseUrl}/admin/gift-cards`, {
        amountCents: Math.round(v.amount * 100),
        currency: v.currency,
        recipientEmail: v.recipientEmail || undefined,
        message: v.message || undefined,
      })
      .subscribe({
        next: (row) => {
          this.issuing.set(false);
          this.issued.set(row);
        },
        error: (err) => {
          this.issuing.set(false);
          this.error.set(extractMessage(err) ?? this.translate.instant('common.genericError'));
        },
      });
  }

  /** Clears the receipt so another card can be issued without a reload. */
  again(): void {
    this.issued.set(null);
    this.form.controls.amount.reset();
    this.form.controls.recipientEmail.reset('');
    this.form.controls.message.reset('');
  }
}
